language: cpp
dist: bionic

git:
  depth: 1

matrix:
  include:
    - env: CXX="g++-7" CC="gcc-7" USE_GLFW=1
      os: linux
      addons:
        apt:
          packages: ['g++-7', 'libglfw3-dev', 'libgles2-mesa-dev']
          sources: ['ubuntu-toolchain-r-test']

    - env: CXX="clang++-6.0" CC="clang-6.0"
      os: linux
      addons:
        apt:
          packages: ['clang-6.0', 'cppcheck']
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-bionic-6.0']
      after_success:
        - cppcheck ../src/

before_install:
  - sudo apt-get -y install libopencv-dev

before_script:
  - $CXX --version
  - cmake --version
  - if [[ ${USE_GLFW} ]]; then export CMAKE_FLAGS="-DUSE_GLFW=1"; fi

script:
    - mkdir -p build && cd build
    - cmake .. ${CMAKE_FLAGS}
    - make -j2
    - make test CTEST_OUTPUT_ON_FAILURE=TRUE

